
environment:
  CONTAINER: stable.world.cli

version: 2
jobs:
  build:
    working_directory: /go/src/github.com/StableWorld/stable.world.cli
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run:
        - go build -o bin/curl commands/curl/main.go
