
environment:
  CONTAINER: stable.world.cli

version: 2
jobs:
  build:
    working_directory: /go/src/github.com/StableWorld/stable.world.cli
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run:
          name: build scurl
          command: go build -o bin/scurl commands/curl/main.go
      - persist_to_workspace:
          root: /go/src/github.com/StableWorld/stable.world.cli
          paths:
            - bin
  deploy:
    working_directory: /go/src/github.com/StableWorld/stable.world.cli
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/StableWorld/stable.world.cli
      - run:
          name: Install gitlab-release
          command: go get github.com/aktau/github-release
          name: Check artifacts
          command: ls -la bin
          name: Edit Release
          command: github-release edit
              -s $GITHUB_TOKEN --user StableWorld --repo stable.world.cli
              --tag v0.0.1 -d "Hello Github Release" -p


workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy
