#!/bin/sh
set -eou pipefail

SCRIPT_VERSION="v0.1"

LOG="$TMPDIR/sw-installer.log"
POSITIONAL=()
VERSION=""
INSTALL_PREFIX="/usr/local/bin"
REPO="StableWorld/stable.world.cli"
OS="darwin"
ARCH="amd64"

VERBOSE=""

logecho(){
  if [ "$VERBOSE" == "yes" ]; then
    echo "$*"
  fi
  echo  "[$(date) ${SCRIPT_VERSION}]" "$*" > $LOG
}

err_report() {
    echo "Error on line $1. Check '$LOG' for details"
}

trap 'err_report $LINENO' ERR


while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
      -v|--version)
      VERSION="$2"
      shift # past argument
      shift # past value
      ;;
      --verbose)
      VERBOSE="yes"
      shift # past argument
      ;;
      --log)
      LOG="$2"
      shift # past argument
      shift # past value
      ;;
      -p|--prefix)
      INSTALL_PREFIX="$2"
      shift # past argument
      shift # past value
      ;;
      *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done
if [ ${#POSITIONAL[@]} -eq 0 ]; then
  POSITIONAL=("scurl")
fi
set -- "${POSITIONAL[@]}" # restore positional parameters
COMMAND=${POSITIONAL[0]}


for var in VERSION LOG INSTALL_PREFIX OS ARCH; do
  logecho "${var}: ${!var}"
done

if [ -z "$VERSION" ]; then
  logecho "Fetch Latest Version ... "
  logecho "https://api.github.com/repos/$REPO/releases/latest"
  VERSION=$(curl  https://api.github.com/repos/$REPO/releases/latest 2> "$LOG" | grep tag_name | sed 's/.*"\(v.*\)".*/\1/g')
fi
logecho "Using version $VERSION"


logecho "Downloading '$COMMAND'"
COMMAND_PATH="$TMPDIR/$COMMAND"
logecho "https://github.com/$REPO/releases/download/$VERSION/$COMMAND-$OS-$ARCH"
curl -o "$COMMAND_PATH" -L --fail "https://github.com/$REPO/releases/download/$VERSION/$COMMAND-$OS-$ARCH" 2> "$LOG"

chmod +x "$COMMAND_PATH"
mv "$COMMAND_PATH" "$INSTALL_PREFIX/$COMMAND"
logecho "Installed $INSTALL_PREFIX/$COMMAND"
